version: '2'

services:

   transmission:
     image: carlosedp/rpi-transmission
     restart: unless-stopped
     ports:
       - "9091:9091"
       - "51413:51413"
       - "51413:51413/udp"
     volumes:
       - transmission_config:/etc/transmission-daemon
       - ${MEDIA}:/volumes/media
       - /etc/localtime:/etc/localtime:ro

   sickrage:
     depends_on:
       - transmission
     image: carlosedp/rpi-sickrage
     restart: unless-stopped
     ports:
       - "8081:8081"
     volumes:
       - sickrage_config:/config
       - ${MEDIA}:/volumes/media
       - /etc/localtime:/etc/localtime:ro
     environment:
       PGID: ${GROUP_ID}
       PUID: ${USER_ID}

   couchpotato:
     depends_on:
       - transmission
     image: carlosedp/rpi-couchpotato
     restart: unless-stopped
     ports:
       - "5050:5050"
     volumes:
       - ${MEDIA}:/volumes/media
       - couchpotato_data:/volumes/data
       - couchpotato_config:/volumes/config
       - /etc/localtime:/etc/localtime:ro

   plex:
     image: jaymoulin/plex
     restart: unless-stopped
     ports:
       - 32400:32400/tcp
       - 3005:3005/tcp
       - 8324:8324/tcp
       - 32469:32469/tcp
       - 1900:1900/udp
       - 32410:32410/udp
       - 32412:32412/udp
       - 32413:32413/udp
       - 32414:32414/udp
     volumes:
       - ${MEDIA}:/media
       - plex_config:/root/Library
       - /etc/localtime:/etc/localtime:ro

   vnstatd:
     image: carlosedp/rpi-vnstatd
     network_mode: "host"
     restart: unless-stopped
     privileged: true
     volumes:
       - vnstat_data:/var/lib/vnstat
       - /etc/localtime:/etc/localtime:ro

   htpcmanager:
     depends_on:
       - vnstatd
     image: carlosedp/rpi-htpcmanager
     restart: unless-stopped
     ports:
       - "8085:8085"
     volumes:
       - htpcmanager_config:/config
       - vnstat_data:/var/lib/vnstat
       - /mnt:/mnt
       - /etc/localtime:/etc/localtime:ro
     environment:
       PGID: ${GROUP_ID}
       PUID: ${USER_ID}
     networks:
       - default
       - traefik
     labels:
       - "traefik.backend=htpcmanager"
       - "traefik.frontend.rule=Host:htpcmanager.cloud.carlosedp.com"
       - "traefik.enable=true"
       - "traefik.port=8085"
       - "traefik.docker.network=monitoring_default"
       - "traefik.default.protocol=http"

volumes:
    transmission_config:
    sickrage_config:
    couchpotato_data:
    couchpotato_config:
    plex_config:
    vnstat_data:
    htpcmanager_config:

networks:
    default:
    traefik:
      external:
        name: monitoring_default
